package com.zxwl.frame.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zxwl.frame.bean.ChatBean;
import com.zxwl.frame.bean.ChatBeanLM;
import com.zxwl.frame.bean.GroupIDBean;
import com.zxwl.frame.bean.LocalFileBean;

import com.zxwl.frame.db.ChatBeanDao;
import com.zxwl.frame.db.ChatBeanLMDao;
import com.zxwl.frame.db.GroupIDBeanDao;
import com.zxwl.frame.db.LocalFileBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatBeanDaoConfig;
    private final DaoConfig chatBeanLMDaoConfig;
    private final DaoConfig groupIDBeanDaoConfig;
    private final DaoConfig localFileBeanDaoConfig;

    private final ChatBeanDao chatBeanDao;
    private final ChatBeanLMDao chatBeanLMDao;
    private final GroupIDBeanDao groupIDBeanDao;
    private final LocalFileBeanDao localFileBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        chatBeanLMDaoConfig = daoConfigMap.get(ChatBeanLMDao.class).clone();
        chatBeanLMDaoConfig.initIdentityScope(type);

        groupIDBeanDaoConfig = daoConfigMap.get(GroupIDBeanDao.class).clone();
        groupIDBeanDaoConfig.initIdentityScope(type);

        localFileBeanDaoConfig = daoConfigMap.get(LocalFileBeanDao.class).clone();
        localFileBeanDaoConfig.initIdentityScope(type);

        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);
        chatBeanLMDao = new ChatBeanLMDao(chatBeanLMDaoConfig, this);
        groupIDBeanDao = new GroupIDBeanDao(groupIDBeanDaoConfig, this);
        localFileBeanDao = new LocalFileBeanDao(localFileBeanDaoConfig, this);

        registerDao(ChatBean.class, chatBeanDao);
        registerDao(ChatBeanLM.class, chatBeanLMDao);
        registerDao(GroupIDBean.class, groupIDBeanDao);
        registerDao(LocalFileBean.class, localFileBeanDao);
    }
    
    public void clear() {
        chatBeanDaoConfig.clearIdentityScope();
        chatBeanLMDaoConfig.clearIdentityScope();
        groupIDBeanDaoConfig.clearIdentityScope();
        localFileBeanDaoConfig.clearIdentityScope();
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

    public ChatBeanLMDao getChatBeanLMDao() {
        return chatBeanLMDao;
    }

    public GroupIDBeanDao getGroupIDBeanDao() {
        return groupIDBeanDao;
    }

    public LocalFileBeanDao getLocalFileBeanDao() {
        return localFileBeanDao;
    }

}
